name: hrDiscord
main: eu.hiveram.hrDiscord.hrDiscord
version: 1.0
api-version: 1.16
depend: [Votifier, LiteBans]
commands:
  hrd:
    description: hrDiscord main command
    usage: /hrd [reload]
  helpop:
    description: Send message to online staff or Discord
    usage: /helpop <message>
    aliases: [hrd helpop, support]
  discord:
    description: Show Discord invite link
    usage: /discord
permissions:
  hrd.seemessages:
    description: Allows to see messages ingame
    default: op
  hrd.reload:
    description: Allows to reload plugin
    default: op
